### PR TITLE
Contact Form setup

### PR DESCRIPTION
**Pull request by OlliesWorld**
I was not sure if all of the other sections need to be on this page. I centered the form and made the borders and button red. I think it may need a thicker boarder and better sizing.

### CODE REVIEW

**Comment by OlliesWorld** [comment]
added the footer and fixed the layout issues on the index page.

**Comment by Rafna** [comment]
@OlliesWorld We don't need everything in the contact page except the header and footer. Before I merge, need corrections in the page.

**Comment by OlliesWorld** [comment]
> @OlliesWorld We don't need everything in the contact page except the header and footer. Before I merge, need corrections in the page.

@Rafna do you want the Navbar, Landing Section and Footer?

**Comment by Rafna** [comment]
All conflicts have resolved

**Pull request merged**
