### PR TITLE
CMS setup

### PR DESCRIPTION
**Pull request by OlliesWorld**
Trying to set up NetlifyCMS and not able to get the collections to pull up on Graphql. I think I am missing something on the gatsby-node or config file.

### CODE REVIEW

**Comment by OlliesWorld** [comment]
This PR has the data being displayed except the image. The styles may need to be adjusted when we add the projects and events.

**Comment by OlliesWorld** [comment]
I pushed a new commit to fix the yml file for the backend back to false. The image still is not displaying.

**Comment by OlliesWorld** [comment]
This PR has all information included but still needs some styling adjustments.

**Comment by OlliesWorld** [comment]
This PR has all the correct info but still may needs some tweaking on the styles.

**Comment by Rafna** [comment]
This looks good.

**Pull request merged**
